language: haskell
before_install:
  - sudo add-apt-repository ppa:ninjablocks/ppa
  - sudo apt-get update -qq
  - sudo apt-get install libczmq-dev libczmq0
script:
  - cd reference; ./build mdworker; ./build mdbroker; cd ..;  ./test/test.sh
